# Omahab native platform applications (Phase 4a).
#
# Every DESIGN app becomes a native systemd service in the closure. All
# per-household values (domain, tokens, client secrets) flow through env
# files under /var/lib/omahab/appenv/ that omahabd renders after
# enrollment; each domain-dependent unit gates on its env file via
# ConditionPathExists so it stays cleanly skipped before enrollment.
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.services.omahab;
  stateDir = "/var/lib/omahab";
  appEnv = "${stateDir}/appenv";
  secretsDir = "${stateDir}/secrets";
  dataDir = "/srv/omahab";
  litellmConfigDir = "${dataDir}/apps/litellm/config";
  litellmConfig = "${litellmConfigDir}/litellm.yaml";
  # Seed mirrors ReconcileModels' empty render (internal/providers/litellm.go):
  # no models, prompts never stored, no message logging, no retries/fallbacks.
  litellmEmptyConfig = pkgs.writeText "litellm-empty.yaml" ''
    # Generated by omahab — do not edit. Rebuildable from provider/alias state.
    model_list:
      []
    general_settings:
      store_prompts_in_spend_logs: false
    litellm_settings:
      turn_off_message_logging: true
    router_settings:
      num_retries: 0
      fallbacks: []
  '';

  # Gate a service on omahabd having rendered its env file.
  gate = bundle: {
    unitConfig.ConditionPathExists = "${appEnv}/${bundle}.env";
  };
in
{
  config = mkIf cfg.enable {
    # ----------------------------------------------------------------
    # Caddy — mutable runtime JSON config, admin API driven by omahabd.
    # ----------------------------------------------------------------
    services.caddy = {
      enable = true;
      configFile = "${stateDir}/caddy/caddy.json";
      # configFile is JSON managed by omahabd; no caddyfile adaptation.
      adapter = null;
      enableReload = true;
      package = pkgs.caddy.withPlugins {
        plugins = [ "github.com/caddy-dns/cloudflare@v0.2.4" ];
        hash = "sha256-dQvk6ezY6TQ1J7PjhCXnThF/SqVgPwBO8/RXzHCY+js=";
      };
    };
    users.users.caddy.extraGroups = [ "omahab-caddy" ];
    users.groups.omahab-caddy = { };
    systemd.tmpfiles.rules = [
      # /var/lib/omahab is 0700 root (omahabd StateDirectory); the caddy
      # config subtree is group-readable by omahab-caddy so the caddy
      # daemon (its own user) can read the JSON omahabd renders.
      "d ${stateDir} 0711 root root - -"
      "d ${stateDir}/caddy 0750 root omahab-caddy - -"
      # Syncthing data dir under /srv/omahab (module chowns it).
      "d ${dataDir}/sync 0755 syncthing syncthing - -"
      "d ${stateDir}/hermes 0700 10000 10000 - -"
      # Immich uses a non-default mediaLocation the module never creates
      # (its `e` rule only repairs existing dirs): pre-create config +
      # library dirs owned by the service user for fresh no-volume installs.
      # The `z` line repairs immich.json after omahabd (root) renders it.
      "d ${dataDir}/apps/immich 0750 immich immich - -"
      "d ${dataDir}/apps/immich/library 0700 immich immich - -"
      "z ${dataDir}/apps/immich/immich.json 0600 immich immich - -"
      # LiteLLM live config (rendered by omahabd, read by the DynamicUser
      # service via a static group distinct from the unit name: DynamicUser
      # implicitly takes user `litellm`, so a static group named `litellm`
      # collides (217/USER "already exists"). `litellm-cfg` avoids it.
      # `d` owns the dir; `C` seeds the empty table once (only if missing,
      # at boot, outside the unit sandbox — ExecStartPre cannot write into
      # the unit's own ReadOnlyPaths).
      "d ${dataDir}/apps/litellm/config 0750 root litellm-cfg - -"
      "d ${dataDir}/apps/litellm/config/secrets 0750 root litellm-cfg - -"
      "C ${dataDir}/apps/litellm/config/litellm.yaml 0640 root litellm-cfg - ${litellmEmptyConfig}"
    ];
    # Root-owned oneshot prepares the caddy config tree before caddy
    # starts (caddy runs as its own user; it cannot create the root
    # state subtree). omahabd later drives the config via the admin API.
    systemd.services.omahab-caddy-init = {
      description = "Prepare Omahab caddy config tree";
      before = [ "caddy.service" ];
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = pkgs.writeShellScript "omahab-caddy-init" ''
          mkdir -p "${stateDir}/caddy"
          chmod 0711 "${stateDir}"
          chown root:omahab-caddy "${stateDir}/caddy"
          chmod 0750 "${stateDir}/caddy"
          if [ ! -s "${stateDir}/caddy/caddy.json" ]; then
            umask 027
            printf '%s' '{"admin":{"listen":"127.0.0.1:2019"}}' > "${stateDir}/caddy/caddy.json"
            chown root:omahab-caddy "${stateDir}/caddy/caddy.json"
          fi
        '';
      };
    };
    systemd.services.caddy = {
      after = [ "omahab-caddy-init.service" ];
      requires = [ "omahab-caddy-init.service" ];
      serviceConfig = {
        EnvironmentFile = [ "-${appEnv}/caddy.env" ];
      };
    };

    # ----------------------------------------------------------------
    # Pocket ID — passkey-first OIDC IdP. Domain-gated.
    #
    # NOTE: the nixpkgs module loads EnvironmentFile =
    # [ environmentFile settingsFile ], so its settings defaults
    # (notably APP_URL=http://localhost) clobber the enrollment-time
    # values omahabd renders into pocket-id.env — pocket-id then
    # advertises rp.id "localhost" and browsers refuse passkey
    # creation on the real domain. Our file must win: it is
    # domain-dependent (unknown at build time), so force it last.
    # ----------------------------------------------------------------
    services.pocket-id = {
      enable = true;
      environmentFile = "${appEnv}/pocket-id.env";
      # Domain-independent; baked in so a future reorder can't silently
      # untrust the proxy headers again.
      settings.TRUST_PROXY = true;
    };
    systemd.services.pocket-id = gate "pocket-id" // {
      serviceConfig.EnvironmentFile = mkForce [ "${appEnv}/pocket-id.env" ];
    };

    # ----------------------------------------------------------------
    # Forgejo — git + CI. Domain-gated.
    # ----------------------------------------------------------------
    services.forgejo = {
      enable = true;
      database.type = "postgres";
      database.createDatabase = true;
      # New repos (incl. omahabd-provisioned mirrors) default to `master`.
      settings.repository.DEFAULT_BRANCH = "master";
    };
    systemd.services.forgejo = {
      serviceConfig = {
        # omahabd writes FORGEJO__SERVER__ROOT_URL etc. here.
        EnvironmentFile = [ "-${appEnv}/forgejo.env" ];
      };
    } // (gate "forgejo");

    # ----------------------------------------------------------------
    # Woodpecker CI — server + one agent on the rootless podman socket.
    # ----------------------------------------------------------------
    services.woodpecker-server = {
      enable = true;
      environmentFile = [ "${appEnv}/woodpecker.env" ];
    };
    systemd.services.woodpecker-server = gate "woodpecker";

    services.woodpecker-agents.agents.docker = {
      enable = true;
      environment = {
        WOODPECKER_BACKEND = "docker";
        DOCKER_HOST = "unix:///run/omahab-builder/podman.sock";
      };
      # environmentFile here does not accept the "-" prefix; the agent
      # tolerates a missing file only via systemd-level config below.
      environmentFile = [ "${appEnv}/woodpecker.env" ];
      extraGroups = [ "omahab-builder" ];
    };
    # The agent must be a STATIC user: DynamicUser silently drops
    # SupplementaryGroups (live 2026-09-12: agent denied on podman.sock),
    # so the omahab-builder group above never applies to a dynamic unit.
    users.users."woodpecker-agent-docker" = {
      isSystemUser = true;
      group = "woodpecker-agent-docker";
      extraGroups = [ "omahab-builder" ];
    };
    users.groups."woodpecker-agent-docker" = { };
    systemd.services."woodpecker-agent-docker" = mkMerge [
      (gate "woodpecker")
      {
        serviceConfig = {
          DynamicUser = mkForce false;
          User = "woodpecker-agent-docker";
          Group = "woodpecker-agent-docker";
        };
      }
    ];

    # ----------------------------------------------------------------
    # Immich — photos. OAuth config file written by omahabd.
    # ----------------------------------------------------------------
    services.immich = {
      enable = true;
      mediaLocation = "${dataDir}/apps/immich/library";
      # Module default "localhost" resolves to ::1 first: the server binds
      # v6 only and the v4 health probe never connects. Pin v4 loopback in
      # the closure itself (flows to IMMICH_HOST).
      host = "127.0.0.1";
      # Skip the initial admin-account wizard: OIDC (Pocket ID, autoRegister)
      # provisions users on first login, so the local setup step is dead
      # weight (immich-app/immich#18847, IMMICH_ALLOW_SETUP=false upstream).
      # Safe with passwordLogin already disabled in immich.json — no local
      # recovery path is removed.
      environment.IMMICH_ALLOW_SETUP = "false";
    };
    # Non-default mediaLocation is not created by the module (its tmpfiles
    # `e` rule only repairs existing dirs): pre-create the config + library
    # dirs owned by the service user so fresh no-volume installs start with
    # zero guest hand-fix (see tmpfiles.rules above). The `z` line repairs
    # immich.json ownership after omahabd (root) renders it.
    systemd.services.immich-server = {
      environment.IMMICH_CONFIG_FILE = "${dataDir}/apps/immich/immich.json";
      serviceConfig.BindReadOnlyPaths = [ "${dataDir}/apps/immich/immich.json" ];
    } // (gate "immich");

    # ----------------------------------------------------------------
    # Paperless-ngx — documents. Domain-gated (PAPERLESS_URL + OIDC JSON).
    # ----------------------------------------------------------------
    services.paperless = {
      enable = true;
      database.createLocally = true;
      configureTika = true;
      dataDir = "${dataDir}/apps/paperless";
      environmentFile = "${appEnv}/paperless-ngx.env";
    };
    systemd.services."paperless-secret-key" = gate "paperless-ngx";
    systemd.services.paperless-web = gate "paperless-ngx";
    systemd.services.paperless-consumer = gate "paperless-ngx";
    systemd.services.paperless-scheduler = gate "paperless-ngx";
    systemd.services."paperless-task-queue" = gate "paperless-ngx";
    # Gotenberg defaults to :3000, colliding with Forgejo (catalog probe,
    # native ports, and the omahabd fallback URL all expect Forgejo on 3000;
    # the loser serves nothing while systemd reports active). Paperless
    # derives PAPERLESS_TIKA_GOTENBERG_ENDPOINT from this port, so the move
    # follows automatically.
    services.gotenberg.port = 3001;

    # ----------------------------------------------------------------
    # Appliance scope: no shell-driven reconfiguration on the box (managed
    # via WebUI/API; installer tooling stays on the live ISO). Drops
    # nixos-install/-enter/-generate-config/-rebuild and their perl envs
    # from the installed closure (faster install, smaller disk).
    system.disableInstallerTools = true;
    # Threaded initrd compression: zstd -10 single-threaded is the
    # default; the 2-vCPU target compresses ~2x faster with -T2.
    # Decompression at boot is identical. The initrd is per-install
    # (hardware modules) either way, so no cache is lost.
    boot.initrd.compressorArgs = [ "-10" "-T2" ];
    # ----------------------------------------------------------------
    # Karakeep — bookmarks. Domain-gated (NextAuth + OIDC).
    # ----------------------------------------------------------------
    services.karakeep = {
      enable = true;
      environmentFile = "${appEnv}/karakeep.env";
      # Upstream defaults to :3000, colliding with Forgejo. Native-port
      # contract (internal/apps/native_ports.go) assigns karakeep :3010.
      extraEnvironment.PORT = "3010";
      # 0.33.2 over pinned nixpkgs' 0.33.1 (AI-relevant: INFERENCE_TEXT_MODEL
      # default gpt-4.1-mini -> gpt-5.6-luna, conditional
      # INFERENCE_USE_MAX_COMPLETION_TOKENS default; plus chrome/node/crawler
      # fixes). Scoped package override, not an overlay: the module exposes
      # `package` for exactly this. Drop when the pin moves past 0.33.2.
      package = pkgs.karakeep.overrideAttrs (old: rec {
        version = "0.33.2";
        src = pkgs.fetchFromGitHub {
          owner = "karakeep-app";
          repo = "karakeep";
          tag = "cli/v${version}";
          hash = "sha256-NsVe8jyGjXZ4fvQqxwHqHlTpaAD89+76rx0TsyFPTjs=";
        };
        pnpmDeps = pkgs.fetchPnpmDeps {
          pname = "karakeep";
          inherit version src;
          patches = old.patches;
          pnpm = pkgs.pnpm_11;
          fetcherVersion = 4;
          hash = "sha256-BcEhsyRENarAhF9MyHdDjSycchJ0vm/78FbE78Gl19E=";
        };
      });
    };
    systemd.services.karakeep-web = {
      partOf = lib.mkForce [ ];
    } // gate "karakeep";
    systemd.services.karakeep-workers = {
      partOf = lib.mkForce [ ];
    } // gate "karakeep";
    # Remove obsolete PartOf (phantom aggregate).
    systemd.services.karakeep-init.partOf = lib.mkForce [ ];
    systemd.services.karakeep-browser.partOf = lib.mkForce [ ];

    # ----------------------------------------------------------------
    # Syncthing — no domain dependency, starts at boot.
    # ----------------------------------------------------------------
    services.syncthing = {
      enable = true;
      overrideDevices = false;
      overrideFolders = false;
      dataDir = "${dataDir}/sync";
      guiAddress = "127.0.0.1:8384";
    };

    # ----------------------------------------------------------------
    # ntfy — push notifications. base-url is runtime state.
    # ----------------------------------------------------------------
    services.ntfy-sh = {
      enable = true;
      settings = {
        listen-http = "127.0.0.1:2586";
        # base-url is runtime state (domain); supplied via NTFY_BASE_URL in
        # the environment file. Module default avoids the empty value.
        base-url = lib.mkDefault "http://localhost";
      };
      environmentFile = "${appEnv}/ntfy.env";
    };
    systemd.services.ntfy-sh = gate "ntfy";

    # ----------------------------------------------------------------
    # LiteLLM — model gateway. Config rendered by omahabd; its env file
    # carries the master key + DB URL. Domain-gated.
    #
    # fastapi pin: litellm 1.97.0 imports the private helper
    # get_flat_dependant from fastapi (proxy/management_v1/common.py),
    # which fastapi removed in 0.140.7, while litellm's stated requirement
    # (fastapi>=0.136.3,<1.0) still admits the locked 0.141.1 — so the
    # stock package fails at import. 0.140.6 is the newest fastapi that
    # still ships get_flat_dependant with the call signature litellm uses
    # (skip_repeats=... returning .query_params), and it satisfies both
    # litellm's floor and its own (starlette>=0.46.0). Scoped to this
    # service via overrideScope so no other closure changes.
    # ----------------------------------------------------------------
    services.litellm = {
      enable = true;
      # Native-port contract (internal/apps/native_ports.go + gateway
      # BaseURL 127.0.0.1:4000): the nixpkgs module defaults to 8080,
      # which collides with the ONCE proxy convention and breaks the
      # health probe, core_apps, and the admin-invite gate.
      port = 4000;
      package = pkgs.litellm.override {
        python3Packages = pkgs.python3Packages.overrideScope (
          _self: super: {
            fastapi = super.fastapi.overridePythonAttrs (_old: rec {
              version = "0.140.6";
              src = pkgs.fetchFromGitHub {
                owner = "tiangolo";
                repo = "fastapi";
                tag = version;
                hash = "sha256-ZWLXNHmM2uGE5y7hLYW4zNSeCGo9d9X2KNT70aXK6W0=";
              };
            });
            # a2a-sdk 0.3.26: its suite runs at build time via
            # installCheckPhase (doInstallCheck defaults true), and one
            # telemetry assertion fails on Linux/python3.14 in this pin:
            # tests/utils/test_telemetry.py::
            # test_trace_function_sync_attribute_extractor_error_logged.
            # Same test is already disabled on Darwin upstream, so this
            # extends that lack of trust to Linux — the other ~820 tests
            # still run and gate the build.
            a2a-sdk = super.a2a-sdk.overridePythonAttrs (old: {
              disabledTests = (old.disabledTests or [ ]) ++ [
                "test_trace_function_sync_attribute_extractor_error_logged"
              ];
            });
          }
        );
      };
      environmentFile = "${appEnv}/litellm.env";
    };
    # The nixpkgs module bakes --config from its immutable `settings`
    # (model_list: [] forever), while omahabd renders the live routing
    # table to /srv on every credential/alias change. Run the mutable
    # file instead (caddy-style: omahabd owns the content, systemd owns
    # path). DynamicUser keeps an ephemeral UID, so the file stays
    # group-readable via a static `litellm-cfg` group (NOT `litellm`:
    # DynamicUser implicitly takes user `litellm`): tmpfiles owns the dir
    # and seeds the empty table once (`C` only-if-missing), the renderer
    # chgrps each render.
    users.groups.litellm-cfg = { };
    systemd.services.litellm = mkMerge [
      (gate "litellm")
      {
        serviceConfig = {
          # DynamicUser allocates an ephemeral UID and refuses a static
          # Group= ("already exists"); a static *supplementary* group is
          # the supported combination for group-readable files, provided
          # the group name differs from the dynamic user name.
          SupplementaryGroups = [ "litellm-cfg" ];
          ReadOnlyPaths = [ litellmConfigDir ];
          ExecStart = mkForce (
            let l = config.services.litellm; in
            "${l.package}/bin/litellm --host ${l.host} --port ${toString l.port} --config ${litellmConfig}"
          );
        };
      }
    ];

    # ----------------------------------------------------------------
    # Hermes — upstream nousresearch/hermes-agent. Loopback-only.
    # Image is part of the closure via imageFile (no --pull=never).
    # Tag 0.21.0 requested by spec; upstream currently only publishes
    # :latest / dated v2026.* tags. Pinned by digest of latest at time of
    # implementation (sha256:a7e2ed27163b31f30f0e9858018df36eed22dd14b4db4a9d574646f1dd3a9a21).
    # Resolved via `docker pull nousresearch/hermes-agent:latest` on
    # 2026-09-02; refreshed via `nix-prefetch-docker` on 2026-09-03
    # (prefetch output hash used directly as the SRI hash).
    virtualisation.oci-containers.backend = "docker";
    virtualisation.oci-containers.containers.hermes = {
      image = "nousresearch/hermes-agent:0.21.0";
      imageFile = pkgs.dockerTools.pullImage {
        imageName = "nousresearch/hermes-agent";
        imageDigest = "sha256:a7e2ed27163b31f30f0e9858018df36eed22dd14b4db4a9d574646f1dd3a9a21";
        sha256 = "sha256-/mgAE2YWuo1jN2hfEz0MgcCcYLoAbKr7/B4Pp81Fic0=";
        finalImageName = "nousresearch/hermes-agent";
        finalImageTag = "0.21.0";
      };
      cmd = [ "gateway" "run" ];
      environmentFiles = [ "${appEnv}/hermes.env" ];
      volumes = [ "/var/lib/omahab/hermes:/opt/data" ];
      # Host networking: the gateway must fetch OIDC discovery from the
      # public issuer (https://id.<domain>, a Tailscale IP) exactly like
      # native services do — from the default bridge that fetch times out
      # (live 2026-09-12: hermes "OIDC discovery unreachable", while
      # Karakeep in the host netns succeeds). Dashboard/API stay
      # loopback-only via HERMES_*_HOST=127.0.0.1 in the rendered env, on
      # the same host ports as before, so no `ports` remap applies
      # (host mode ignores it).
      extraOptions = [ "--network=host" ];
    };
    systemd.services.docker-hermes = gate "hermes";
    # ----------------------------------------------------------------
    # Embedding worker — in-repo Python, own hardened unit.
    # ----------------------------------------------------------------
    systemd.services.omahab-embedding-worker = {
      description = "Omahab embedding worker (loopback/UDS)";
      documentation = [ "https://github.com/davidgilesgt/omahab" ];
      after = [
        "network.target"
        "omahab-embedding-init.service"
      ];
      requires = [ "omahab-embedding-init.service" ];
      wantedBy = [ "multi-user.target" ];
      # The worker serves no model until omahabd writes the pinned-models
      # config (dashboard setup step); a default empty config keeps it up.

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.embeddingWorkerPackage}/bin/omahab-embedding-worker --config /var/lib/omahab/embedding/pinned_models.json --transport uds --socket /run/omahab-embedding/embedding.sock";
        User = "omahab-embedding";
        Group = "omahab-embedding";
        RuntimeDirectory = "omahab-embedding";
        RuntimeDirectoryMode = "0750";
        Restart = "on-failure";
        RestartSec = 5;
        NoNewPrivileges = true;
        PrivateTmp = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        ReadWritePaths = [ "/run/omahab-embedding" ];
        StateDirectory = "omahab-embedding";
      };
    };
    users.users.omahab-embedding = {
      isSystemUser = true;
      group = "omahab-embedding";
    };
    users.groups.omahab-embedding = { };

    # Root-prepared embedding config: the worker runs as its own user and
    # cannot create /var/lib/omahab subtrees. omahab-embedding-init writes
    # the empty default; omahabd later replaces it with the chosen model.
    systemd.services.omahab-embedding-init = {
      description = "Prepare Omahab embedding worker config";
      before = [ "omahab-embedding-worker.service" ];
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = pkgs.writeShellScript "omahab-embedding-init" ''
          mkdir -p /var/lib/omahab/embedding
          chown root:omahab-embedding /var/lib/omahab/embedding
          chmod 0750 /var/lib/omahab/embedding
          if [ ! -s /var/lib/omahab/embedding/pinned_models.json ]; then
            printf '%s' '{"models":{},"models_base_dir":"/var/lib/omahab/models","allow_test_adapter":false}' > /var/lib/omahab/embedding/pinned_models.json
            chown root:omahab-embedding /var/lib/omahab/embedding/pinned_models.json
            chmod 0640 /var/lib/omahab/embedding/pinned_models.json
          fi
        '';
      };
    };

    # ----------------------------------------------------------------
    # Storage placement: mounts volumes recorded in storage.json before
    # app units start. No-op when the file is absent (root disk holds
    # everything; the wizard step is skippable).
    # ----------------------------------------------------------------
    systemd.services.omahab-storage = {
      description = "Mount Omahab storage volumes (storage.json)";
      wantedBy = [ "multi-user.target" ];
      before = [
        "postgresql.service"
        "immich-server.service"
        "syncthing.service"
      ];
      unitConfig = {
        ConditionPathExists = "${stateDir}/storage.json";
        RequiresMountsFor = [ "/srv/omahab" ];
      };
      serviceConfig = {
        Type = "oneshot";
        ExecStart = pkgs.writeShellScript "omahab-storage" ''
          set -euo pipefail
          CFG="${stateDir}/storage.json"
          mkdir -p /srv/omahab/disks
          ${pkgs.jq}/bin/jq -c '.[]' "$CFG" | while read -r entry; do
            vol=$(echo "$entry" | ${pkgs.jq}/bin/jq -r '.volume')
            uuid=$(echo "$entry" | ${pkgs.jq}/bin/jq -r '.fs_uuid')
            mnt="/srv/omahab/disks/$uuid"
            mkdir -p "$mnt"
            if ! mountpoint -q "$mnt"; then
              mount -U "$uuid" "$mnt"
            fi
            if [ "$vol" = "media" ]; then
              mkdir -p "$mnt/media" /srv/omahab/apps/immich/library
              mountpoint -q /srv/omahab/apps/immich/library || mount --bind "$mnt/media" /srv/omahab/apps/immich/library
            fi
          done
        '';
        RemainAfterExit = true;
      };
    };

    # ----------------------------------------------------------------
    # Shared PostgreSQL — per-app databases provisioned by modules above
    # plus LiteLLM's (the litellm module does not manage it).
    # ----------------------------------------------------------------
    services.postgresql = {
      enable = true;
      ensureDatabases = [ "litellm" "woodpecker-server" ];
      ensureUsers = [
        {
          name = "litellm";
          ensureDBOwnership = true;
        }
        # Woodpecker server runs under DynamicUser (ephemeral UID), so socket
        # peer auth is impossible: it connects over TCP scram with the role
        # password omahabd syncs from the materialized secret at install.
        {
          name = "woodpecker-server";
          ensureDBOwnership = true;
        }
      ];
    };
    # ----------------------------------------------------------------
    # Redis for LiteLLM cache.
    # ----------------------------------------------------------------
    services.redis.servers.omahab = {
      enable = true;
      port = 6379;
    };

    # ----------------------------------------------------------------
    # Restic REST server — per-machine backups, append-only, private repos.
    # Data under /srv/omahab/machine-backups, htpasswd at
    # /var/lib/omahab/machine-backups.htpasswd. Caddy route
    # backup.<domain> -> 127.0.0.1:8500 via catalog bundle restic-server
    # (private, max private). The server is append-only so forget only
    # marks; prune is never run from clients.
    # ----------------------------------------------------------------
    services.restic.server = {
      enable = true;
      listenAddress = "127.0.0.1:8500";
      dataDir = "/srv/omahab/machine-backups";
      appendOnly = true;
      privateRepos = true;
      htpasswd-file = "/var/lib/omahab/machine-backups.htpasswd";
    };
    # Gate on htpasswd existence: missing = not configured (clean skip),
    # malformed file remains a real error. Socket activation retained.
    systemd.services.restic-rest-server.unitConfig.ConditionPathExists = "/var/lib/omahab/machine-backups.htpasswd";
  };
}
