package controlplane

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"log"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/omahab/omahab/internal/apitypes"
	"github.com/omahab/omahab/internal/providers"
)

var (
	handoffMu sync.Mutex
	seedMu    sync.Mutex
)

const (
	handoffVersionKey = "version"
	handoffVersionVal = "1"
	handoffPhaseKey   = "phase"
	handoffErrorKey   = "error"

	handoffPhasePreparing = "preparing"
	handoffPhaseImported  = "imported"
	handoffPhaseCutover   = "cutover"
	handoffPhaseComplete  = "complete"
)

var seedRoles = []string{
	providers.AliasFast,
	providers.AliasBalanced,
	providers.AliasReasoning,
	providers.AliasSummarization,
}

var modelSetupAliases = []string{
	providers.AliasFast,
	providers.AliasBalanced,
	providers.AliasReasoning,
	providers.AliasSummarization,
	providers.AliasEmbedding,
	providers.AliasKarakeep,
}

func sha256Hex(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])
}

func migratedModelID(alias string) string {
	return "omahab-migrated-" + sha256Hex(alias)
}

func migratedCredentialName(legacyID string) string {
	return "omahab-migrated-" + sha256Hex(strings.TrimSpace(legacyID))
}

func seedCredentialName(sourceID string) string {
	return "omahab-seed-" + sha256Hex(strings.TrimSpace(sourceID))
}

func seedRoleID(alias string) string {
	return "omahab-seed-" + sha256Hex(strings.TrimSpace(alias))
}

// --- journal ---

func (b *Backend) handoffGet(ctx context.Context, key string) (string, error) {
	if b.db == nil {
		return "", fmt.Errorf("db not configured")
	}
	var v string
	err := b.db.QueryRowContext(ctx, `SELECT value FROM provider_model_handoff WHERE key = ?`, key).Scan(&v)
	if err != nil {
		return "", err
	}
	return v, nil
}

func (b *Backend) handoffSet(ctx context.Context, key, value string) error {
	if b.db == nil {
		return fmt.Errorf("db not configured")
	}
	_, err := b.db.ExecContext(ctx, `INSERT INTO provider_model_handoff(key, value) VALUES(?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`, key, value)
	return err
}

func (b *Backend) handoffDel(ctx context.Context, key string) error {
	if b.db == nil {
		return nil
	}
	_, _ = b.db.ExecContext(ctx, `DELETE FROM provider_model_handoff WHERE key = ?`, key)
	return nil
}

func (b *Backend) handoffPhase(ctx context.Context) string {
	v, err := b.handoffGet(ctx, handoffPhaseKey)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(v)
}

func (b *Backend) handoffSetPhase(ctx context.Context, phase string) error {
	if err := b.handoffSet(ctx, handoffVersionKey, handoffVersionVal); err != nil {
		return err
	}
	return b.handoffSet(ctx, handoffPhaseKey, phase)
}

func (b *Backend) handoffSetError(ctx context.Context, msg string) {
	msg = strings.TrimSpace(msg)
	if msg == "" {
		_ = b.handoffDel(ctx, handoffErrorKey)
		return
	}
	// Safe text only: callers must never include secrets.
	if len(msg) > 500 {
		msg = msg[:500]
	}
	_ = b.handoffSet(ctx, handoffErrorKey, msg)
}

// --- static bootstrap + salt ---

func staticLitellmBootstrap() string {
	return `# Generated by omahab — do not edit. Native DB ownership; models live in LiteLLM database.
model_list: []
general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: false
litellm_settings:
  turn_off_message_logging: true
router_settings:
  num_retries: 0
  fallbacks: []
`
}

func (b *Backend) litellmConfigPaths() (finalPath, snapshotPath string) {
	dir := b.gatewayConfigDir()
	return filepath.Join(dir, "litellm.yaml"), filepath.Join(dir, "omahab-pre-handoff.yaml")
}

func (b *Backend) snapshotPreHandoffYAML() error {
	finalPath, snapshotPath := b.litellmConfigPaths()
	if _, err := os.Stat(snapshotPath); err == nil {
		return nil // never overwrite recovery snapshot on retry
	}
	raw, err := os.ReadFile(finalPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read live litellm config: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(snapshotPath), 0o700); err != nil {
		return fmt.Errorf("mkdir config dir: %w", err)
	}
	if err := os.WriteFile(snapshotPath, raw, 0o600); err != nil {
		return fmt.Errorf("write pre-handoff snapshot: %w", err)
	}
	_ = os.Chmod(snapshotPath, 0o600)
	return nil
}

func (b *Backend) writeStaticBootstrapYAML() error {
	finalPath, _ := b.litellmConfigPaths()
	want := staticLitellmBootstrap()
	if raw, err := os.ReadFile(finalPath); err == nil && string(raw) == want {
		providers.ShareGatewayConfig(finalPath)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(finalPath), 0o700); err != nil {
		return fmt.Errorf("mkdir config dir: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(finalPath), "litellm.yaml.*")
	if err != nil {
		return fmt.Errorf("stage static config: %w", err)
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(want); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return fmt.Errorf("write static config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return fmt.Errorf("close static config: %w", err)
	}
	_ = os.Chmod(tmpName, 0o600)
	if err := os.Rename(tmpName, finalPath); err != nil {
		_ = os.Remove(tmpName)
		return fmt.Errorf("activate static config: %w", err)
	}
	providers.ShareGatewayConfig(finalPath)
	return nil
}

// restorePreHandoffYAML puts the pre-handoff gateway config back after a
// failed cutover verify, so the gateway never serves the empty bootstrap
// with nothing behind it. No snapshot (fresh installs) is a no-op.
func (b *Backend) restorePreHandoffYAML() error {
	finalPath, snapshotPath := b.litellmConfigPaths()
	raw, err := os.ReadFile(snapshotPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read pre-handoff snapshot: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(finalPath), 0o700); err != nil {
		return fmt.Errorf("mkdir config dir: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(finalPath), "litellm.yaml.*")
	if err != nil {
		return fmt.Errorf("stage restored config: %w", err)
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(raw); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return fmt.Errorf("write restored config: %w", err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName)
		return fmt.Errorf("close restored config: %w", err)
	}
	_ = os.Chmod(tmpName, 0o600)
	if err := os.Rename(tmpName, finalPath); err != nil {
		_ = os.Remove(tmpName)
		return fmt.Errorf("activate restored config: %w", err)
	}
	providers.ShareGatewayConfig(finalPath)
	return nil
}

// ensureLitellmSalt resolves the effective LITELLM_SALT_KEY per freeze semantics
// and persists it through the broker. It never regenerates during setup and
// never logs secret material. Returns the chosen salt (possibly empty when
// neither active nor broker material exists yet; caller then leaves env alone).
func (b *Backend) ensureLitellmSalt(ctx context.Context, existing map[string]string) string {
	active := strings.TrimSpace(existing["LITELLM_SALT_KEY"])
	if active != "" {
		// Keep byte-for-byte; mirror into broker so retries converge.
		if b.secrets != nil {
			if cur, err := b.secrets.RevealByName(ctx, "platform-app", "litellm_salt_key"); err != nil || strings.TrimSpace(cur) != active {
				_ = upsertSecret(ctx, b.secrets, "platform-app", "litellm_salt_key", active)
			}
		}
		return active
	}
	// No active salt: freeze current effective master key before any change.
	effectiveMaster := strings.TrimSpace(existing["LITELLM_MASTER_KEY"])
	if effectiveMaster == "" && b.secrets != nil {
		if v, err := b.secrets.RevealByName(ctx, "platform-app", "litellm_master_key"); err == nil {
			effectiveMaster = strings.TrimSpace(v)
		}
	}
	if effectiveMaster != "" {
		if b.secrets != nil {
			_ = upsertSecret(ctx, b.secrets, "platform-app", "litellm_salt_key", effectiveMaster)
		}
		return effectiveMaster
	}
	// Fresh install: use already-declared broker secret (materialized from
	// catalog secret_sources); never generate here.
	if b.secrets != nil {
		if v, err := b.secrets.RevealByName(ctx, "platform-app", "litellm_salt_key"); err == nil && strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// --- provider identity ---

var standardAPIHosts = map[string]string{
	providers.ProviderOpenAI:     "api.openai.com",
	providers.ProviderAnthropic:  "api.anthropic.com",
	providers.ProviderOpenRouter: "openrouter.ai",
	providers.ProviderXAI:        "api.x.ai",
}

func normalizeOrigin(apiBase string) string {
	apiBase = strings.TrimSpace(apiBase)
	if apiBase == "" {
		return ""
	}
	u, err := url.Parse(apiBase)
	if err != nil || strings.TrimSpace(u.Host) == "" {
		// Fall back to raw lowercased host-like prefix.
		lower := strings.ToLower(apiBase)
		lower = strings.TrimPrefix(lower, "https://")
		lower = strings.TrimPrefix(lower, "http://")
		if i := strings.Index(lower, "/"); i >= 0 {
			lower = lower[:i]
		}
		if i := strings.Index(lower, ":"); i >= 0 {
			lower = lower[:i]
		}
		return strings.TrimSpace(lower)
	}
	host := strings.ToLower(strings.TrimSpace(u.Hostname()))
	return host
}

func knownProvider(p string) bool {
	switch strings.ToLower(strings.TrimSpace(p)) {
	case providers.ProviderOpenAI, providers.ProviderAnthropic, providers.ProviderOpenRouter, providers.ProviderChatGPT, providers.ProviderXAI:
		return true
	}
	return false
}

// resolveProviderIdentity maps native deployment metadata to a consent identity.
// Built-in standard endpoints preserve plain provider keys; custom api_base
// endpoints qualify by normalized origin so consent to OpenAI is never reused
// for a different OpenAI-compatible host. Unknown/opaque routing is unresolved.
func resolveProviderIdentity(d providers.GatewayDeployment) (string, bool) {
	params := d.LitellmParams
	if params == nil {
		params = map[string]any{}
	}
	modelStr, _ := params["model"].(string)
	modelStr = strings.TrimSpace(modelStr)
	customProvider := ""
	if v, ok := params["custom_llm_provider"].(string); ok {
		customProvider = strings.ToLower(strings.TrimSpace(v))
	}
	infoProvider := strings.ToLower(strings.TrimSpace(d.ModelInfo.LitellmProvider))
	apiBase := ""
	if v, ok := params["api_base"].(string); ok {
		apiBase = strings.TrimSpace(v)
	}
	base := ""
	if knownProvider(customProvider) {
		base = customProvider
	} else if knownProvider(infoProvider) {
		base = infoProvider
	} else if modelStr != "" {
		if i := strings.Index(modelStr, "/"); i > 0 {
			prefix := strings.ToLower(strings.TrimSpace(modelStr[:i]))
			if knownProvider(prefix) {
				base = prefix
			}
		}
	}
	if base == "" {
		return "", false
	}
	// Normalize chatgpt/xai synonyms that LiteLLM may enrich.
	if base == "xai" {
		base = providers.ProviderXAI
	}
	if apiBase == "" {
		return base, true
	}
	host := normalizeOrigin(apiBase)
	if host == "" {
		return "", false
	}
	if std, ok := standardAPIHosts[base]; ok && (host == std || strings.HasSuffix(host, "."+std)) {
		return base, true
	}
	// ChatGPT/XAI subscription deployments carry no api_base; a present
	// api_base on those providers is custom by definition.
	return base + "@" + host, true
}

func deploymentMode(d providers.GatewayDeployment) string {
	return strings.ToLower(strings.TrimSpace(d.ModelInfo.Mode))
}

func isSelectableDeployment(d providers.GatewayDeployment) (provider, mode string, ok bool) {
	if strings.TrimSpace(d.ModelInfo.ID) == "" || strings.TrimSpace(d.ModelName) == "" {
		return "", "", false
	}
	if d.ModelInfo.DBModel != nil && !*d.ModelInfo.DBModel {
		return "", "", false
	}
	if d.ModelInfo.DBModel == nil {
		// Absent db_model is unknown capability; do not guess.
		return "", "", false
	}
	if d.ModelInfo.TeamID != nil && strings.TrimSpace(*d.ModelInfo.TeamID) != "" {
		return "", "", false
	}
	if d.ModelInfo.Blocked != nil && *d.ModelInfo.Blocked {
		return "", "", false
	}
	if strings.Contains(d.ModelName, "*") {
		return "", "", false
	}
	if params := d.LitellmParams; params != nil {
		if m, ok := params["model"].(string); ok && strings.Contains(m, "*") {
			return "", "", false
		}
	}
	// Synthetic router deployments never seed chat roles.
	lowerID := strings.ToLower(strings.TrimSpace(d.ModelInfo.ID))
	lowerName := strings.ToLower(strings.TrimSpace(d.ModelName))
	if strings.HasPrefix(lowerID, "router-") || strings.HasPrefix(lowerName, "router-") {
		return "", "", false
	}
	m := deploymentMode(d)
	if m != "chat" && m != "responses" {
		return "", "", false
	}
	params := d.LitellmParams
	if params == nil {
		return "", "", false
	}
	modelStr, _ := params["model"].(string)
	if strings.TrimSpace(modelStr) == "" {
		return "", "", false
	}
	// Embedding-only deployments are never chat sources.
	if m == "embedding" {
		return "", "", false
	}
	prov, ok := resolveProviderIdentity(d)
	if !ok || strings.TrimSpace(prov) == "" {
		return "", "", false
	}
	return prov, m, true
}

// --- management URL ---

func (b *Backend) litellmManagementURL(ctx context.Context) string {
	bundles, domainName, err := b.launchContext(ctx)
	if err != nil || b.apps == nil {
		return ""
	}
	bd, ok := bundles["litellm"]
	if !ok {
		return ""
	}
	list, err := b.apps.List(ctx)
	if err != nil {
		return ""
	}
	for _, st := range list {
		if st.BundleID != "litellm" {
			continue
		}
		if u := applicationLaunchURL(st.Application, bd, domainName); u != "" {
			return u
		}
		return ""
	}
	return ""
}

// --- handoff ---

func (b *Backend) handoffNeedsMigration(ctx context.Context) (bool, error) {
	if b.providers == nil {
		return false, nil
	}
	aliases, err := b.providers.ListAliases(ctx)
	if err != nil {
		return false, err
	}
	creds, err := b.providers.ListCredentials(ctx)
	if err != nil {
		return false, err
	}
	if len(aliases) == 0 {
		// Still migrate when API-key material exists without aliases? No
		// routing to preserve; but ensure bootstrap/salt/retirement.
		hasKeys := false
		for _, c := range creds {
			if c == nil {
				continue
			}
			if strings.ToLower(strings.TrimSpace(c.CredentialType)) == providers.CredentialTypeAPIKey {
				hasKeys = true
				break
			}
		}
		if !hasKeys {
			return false, nil
		}
	}
	return true, nil
}

// runProviderHandoff performs the one-time SQLite→LiteLLM ownership migration.
// It is resume-safe, additive until cutover, and never overwrites recovery data.
func (b *Backend) runProviderHandoff(ctx context.Context) error {
	handoffMu.Lock()
	defer handoffMu.Unlock()
	if b.db == nil || b.providers == nil || b.gateway == nil {
		return nil
	}
	phase := b.handoffPhase(ctx)
	if phase == handoffPhaseComplete {
		return nil
	}
	// Ensure version marker.
	if v, err := b.handoffGet(ctx, handoffVersionKey); err != nil || strings.TrimSpace(v) != handoffVersionVal {
		if err := b.handoffSet(ctx, handoffVersionKey, handoffVersionVal); err != nil {
			return fmt.Errorf("handoff journal: %w", err)
		}
	}
	if phase == "" {
		needs, err := b.handoffNeedsMigration(ctx)
		if err != nil {
			msg := "provider model handoff preflight failed; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff preflight: %w; retry setup", err)
		}
		if !needs {
			// No legacy routing: still converge bootstrap/salt, then complete.
			if err := b.snapshotPreHandoffYAML(); err != nil {
				return err
			}
			if err := b.writeStaticBootstrapYAML(); err != nil {
				return err
			}
			if err := b.retireProviderEnv(ctx); err != nil {
				msg := "provider model handoff retirement failed; retry setup"
				b.handoffSetError(ctx, msg)
				return fmt.Errorf("handoff retirement: %w; retry setup", err)
			}
			if err := b.handoffSetPhase(ctx, handoffPhaseComplete); err != nil {
				return err
			}
			b.handoffSetError(ctx, "")
			return nil
		}
		phase = handoffPhasePreparing
		if err := b.handoffSetPhase(ctx, phase); err != nil {
			return err
		}
	}
	// Never republish stale SQLite aliases over native models after cutover.
	if phase == handoffPhaseCutover {
		if err := b.retireProviderEnv(ctx); err != nil {
			msg := "provider model handoff retirement failed; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff retirement: %w; retry setup", err)
		}
		if err := b.handoffSetPhase(ctx, handoffPhaseComplete); err != nil {
			return err
		}
		b.handoffSetError(ctx, "")
		return nil
	}
	if phase != handoffPhasePreparing && phase != handoffPhaseImported {
		msg := "provider model handoff in unknown phase; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("%s", msg)
	}
	if err := b.handoffImport(ctx); err != nil {
		return err
	}
	// Phase is now imported; swap YAML once, verify, cut over, retire.
	if err := b.handoffCutover(ctx); err != nil {
		return err
	}
	if err := b.retireProviderEnv(ctx); err != nil {
		msg := "provider model handoff retirement failed; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff retirement: %w; retry setup", err)
	}
	if err := b.handoffSetPhase(ctx, handoffPhaseComplete); err != nil {
		return err
	}
	b.handoffSetError(ctx, "")
	return nil
}

func (b *Backend) revealLegacySecret(ctx context.Context, c *providers.Credential) (string, error) {
	if c == nil || b.secrets == nil {
		return "", fmt.Errorf("credential %q has no secret material", "")
	}
	id := strings.TrimSpace(string(c.ID))
	if strings.TrimSpace(string(c.SecretID)) != "" {
		v, err := b.secrets.Reveal(ctx, c.SecretID)
		if err != nil {
			return "", fmt.Errorf("credential %q reveal failed", id)
		}
		return v, nil
	}
	v, err := b.secrets.RevealByName(ctx, "provider", "credential."+id)
	if err != nil {
		return "", fmt.Errorf("credential %q reveal failed", id)
	}
	return v, nil
}

// handoffQuarantineReason reports why a legacy alias must not migrate
// ("" = migratable): unknown names, duplicates, dangling references.
func handoffQuarantineReason(name string, seen map[string]bool, credByID map[string]*providers.Credential, credID string) string {
	if !isHandoffAlias(name) {
		return "unsupported alias"
	}
	if seen[name] {
		return "duplicate alias"
	}
	if _, ok := credByID[credID]; !ok {
		return "missing credential"
	}
	return ""
}

// handoffMigratable filters legacy aliases to the migratable set, journaling
// quarantine reasons per alias (handoff key "skipped/<name>") instead of
// failing the whole setup.
func (b *Backend) handoffMigratable(ctx context.Context, aliases []*providers.Alias, credByID map[string]*providers.Credential) []*providers.Alias {
	seen := map[string]bool{}
	out := make([]*providers.Alias, 0, len(aliases))
	for _, a := range aliases {
		if a == nil {
			continue
		}
		name := strings.TrimSpace(a.Name)
		if reason := handoffQuarantineReason(name, seen, credByID, string(a.CredentialID)); reason != "" {
			_ = b.handoffSet(ctx, "skipped/"+name, reason)
			log.Printf("provider model handoff: quarantined alias %q (%s)", name, reason)
			continue
		}
		seen[name] = true
		_ = b.handoffDel(ctx, "skipped/"+name)
		out = append(out, a)
	}
	return out
}

func (b *Backend) handoffImport(ctx context.Context) error {
	aliases, err := b.providers.ListAliases(ctx)
	if err != nil {
		msg := "provider model handoff preflight failed; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff list aliases: %w; retry setup", err)
	}
	creds, err := b.providers.ListCredentials(ctx)
	if err != nil {
		msg := "provider model handoff preflight failed; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff list credentials: %w; retry setup", err)
	}
	credByID := map[string]*providers.Credential{}
	for _, c := range creds {
		if c == nil {
			continue
		}
		credByID[string(c.ID)] = c
	}
	// Filter to the migratable set, quarantining unknown names, duplicates,
	// and dangling credential references in the journal instead of failing
	// the whole setup: one legacy custom alias must never block the rest.
	aliases = b.handoffMigratable(ctx, aliases, credByID)
	native, err := b.gateway.ListModels(ctx)
	if err != nil {
		msg := "LiteLLM gateway unavailable; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff list native models: %w; retry setup", err)
	}
	byID := map[string]providers.GatewayDeployment{}
	byName := map[string][]providers.GatewayDeployment{}
	for _, d := range native {
		byID[strings.TrimSpace(d.ModelInfo.ID)] = d
		byName[strings.TrimSpace(d.ModelName)] = append(byName[strings.TrimSpace(d.ModelName)], d)
	}
	// Conflict check: same public alias name not belonging to this handoff.
	for _, a := range aliases {
		if a == nil {
			continue
		}
		name := strings.TrimSpace(a.Name)
		wantID := migratedModelID(name)
		for _, d := range byName[name] {
			if strings.TrimSpace(d.ModelInfo.ID) == wantID &&
				d.ModelInfo.ExtraString("omahab_handoff") == "1" &&
				d.ModelInfo.ExtraString("omahab_source_alias") == name {
				continue // resumed object
			}
			// Journaled resume also adopts.
			if jv, jerr := b.handoffGet(ctx, "model/"+name); jerr == nil && strings.TrimSpace(jv) == strings.TrimSpace(d.ModelInfo.ID) {
				continue
			}
			msg := "Resolve the conflicting model " + name + " in LiteLLM, then retry setup."
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff conflicting model %q; %s", name, msg)
		}
	}
	if err := b.snapshotPreHandoffYAML(); err != nil {
		return err
	}
	// Migrate API-key credentials first.
	for _, c := range creds {
		if c == nil {
			continue
		}
		if strings.ToLower(strings.TrimSpace(c.CredentialType)) != providers.CredentialTypeAPIKey {
			continue
		}
		legacyID := strings.TrimSpace(string(c.ID))
		wantName := migratedCredentialName(legacyID)
		if jv, jerr := b.handoffGet(ctx, "credential/"+legacyID); jerr == nil && strings.TrimSpace(jv) != "" {
			continue // already journaled
		}
		gwCreds, err := b.gateway.ListGatewayCredentials(ctx)
		if err != nil {
			msg := "LiteLLM gateway unavailable; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff list credentials: %w; retry setup", err)
		}
		adopted := false
		for _, gc := range gwCreds {
			if strings.TrimSpace(gc.CredentialName) != wantName {
				continue
			}
			if strings.TrimSpace(gc.CredentialInfo["omahab_handoff"]) == "1" &&
				strings.TrimSpace(gc.CredentialInfo["omahab_source_credential_id"]) == legacyID {
				adopted = true
				break
			}
			msg := "Resolve the conflicting credential " + wantName + " in LiteLLM, then retry setup."
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff conflicting credential %q; %s", wantName, msg)
		}
		if adopted {
			_ = b.handoffSet(ctx, "credential/"+legacyID, wantName)
			continue
		}
		secret, err := b.revealLegacySecret(ctx, c)
		if err != nil {
			msg := "provider model handoff failed for credential " + legacyID + "; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff reveal credential %q failed; retry setup", legacyID)
		}
		in := providers.GatewayCredentialInput{
			CredentialName:   wantName,
			CredentialInfo:   map[string]string{"omahab_handoff": "1", "omahab_source_credential_id": legacyID},
			CredentialValues: map[string]string{"api_key": secret},
		}
		if err := b.gateway.CreateGatewayCredential(ctx, in); err != nil {
			msg := "provider model handoff failed for credential " + legacyID + "; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff create credential %q: %w; retry setup", legacyID, err)
		}
		_ = b.handoffSet(ctx, "credential/"+legacyID, wantName)
	}
	// Convert aliases additively.
	for _, a := range aliases {
		if a == nil {
			continue
		}
		name := strings.TrimSpace(a.Name)
		wantID := migratedModelID(name)
		if jv, jerr := b.handoffGet(ctx, "model/"+name); jerr == nil && strings.TrimSpace(jv) != "" {
			// Verify resumed object still exists with correct tags; never overwrite.
			if d, ok := byID[strings.TrimSpace(jv)]; ok &&
				d.ModelInfo.ExtraString("omahab_handoff") == "1" &&
				d.ModelInfo.ExtraString("omahab_source_alias") == name {
				continue
			}
			// Journaled but missing/diverged: fall through to recreate check below.
		}
		if d, ok := byID[wantID]; ok {
			if d.ModelInfo.ExtraString("omahab_handoff") == "1" &&
				d.ModelInfo.ExtraString("omahab_source_alias") == name {
				_ = b.handoffSet(ctx, "model/"+name, wantID)
				continue
			}
			msg := "Resolve the conflicting model " + name + " in LiteLLM, then retry setup."
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff conflicting model id %q; %s", wantID, msg)
		}
		cred := credByID[string(a.CredentialID)]
		if cred == nil {
			msg := "provider model handoff found alias " + name + " with missing credential; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff alias %q references unknown credential; retry setup", name)
		}
		provider := strings.ToLower(strings.TrimSpace(cred.Provider))
		credType := strings.ToLower(strings.TrimSpace(cred.CredentialType))
		managedBy := strings.TrimSpace(cred.ManagedBy)
		extRef := ""
		if cred.ExternalRef != nil {
			extRef = strings.TrimSpace(*cred.ExternalRef)
		}
		nativeModel, useOAuth, responsesMode, err := providers.NormalizeNativeModel(provider, credType, managedBy, extRef, a.Model)
		if err != nil {
			msg := "provider model handoff failed for alias " + name + "; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff normalize alias %q: %w; retry setup", name, err)
		}
		params := map[string]any{"model": nativeModel}
		if useOAuth {
			params["use_xai_oauth"] = true
		}
		if credType == providers.CredentialTypeAPIKey {
			params["litellm_credential_name"] = migratedCredentialName(strings.TrimSpace(string(cred.ID)))
		}
		mode := "chat"
		if responsesMode {
			mode = "responses"
		}
		dbTrue := true
		dep := providers.GatewayDeployment{
			ModelName:     name,
			LitellmParams: params,
			ModelInfo: providers.GatewayModelInfo{
				ID:              wantID,
				DBModel:         &dbTrue,
				Mode:            mode,
				LitellmProvider: provider,
				Extra: map[string]any{
					"omahab_handoff":      "1",
					"omahab_source_alias": name,
				},
			},
		}
		if err := b.gateway.CreateModel(ctx, dep); err != nil {
			msg := "provider model handoff failed for alias " + name + "; retry setup"
			b.handoffSetError(ctx, msg)
			return fmt.Errorf("handoff create model %q: %w; retry setup", name, err)
		}
		_ = b.handoffSet(ctx, "model/"+name, wantID)
		// Refresh inventory view for subsequent conflict checks.
		byID[wantID] = dep
		byName[name] = append(byName[name], dep)
	}
	if err := b.handoffSetPhase(ctx, handoffPhaseImported); err != nil {
		return err
	}
	b.handoffSetError(ctx, "")
	return nil
}

func isHandoffAlias(name string) bool {
	switch name {
	case providers.AliasFast, providers.AliasBalanced, providers.AliasReasoning,
		providers.AliasEmbedding, providers.AliasKarakeep, providers.AliasSummarization:
		return true
	}
	return false
}

func (b *Backend) handoffCutover(ctx context.Context) error {
	aliases, err := b.providers.ListAliases(ctx)
	if err != nil {
		msg := "provider model handoff verify failed; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff list aliases: %w; retry setup", err)
	}
	creds, err := b.providers.ListCredentials(ctx)
	if err != nil {
		msg := "provider model handoff verify failed; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff list credentials: %w; retry setup", err)
	}
	credByID := map[string]*providers.Credential{}
	for _, c := range creds {
		if c == nil {
			continue
		}
		credByID[string(c.ID)] = c
	}
	// Verify only what import migrates; quarantined aliases stay on legacy
	// rows and must not fail the cutover.
	wantNames := map[string]string{}
	for _, a := range b.handoffMigratable(ctx, aliases, credByID) {
		name := strings.TrimSpace(a.Name)
		wantNames[name] = migratedModelID(name)
	}
	// Atomic empty-YAML swap + single restart.
	if err := b.writeStaticBootstrapYAML(); err != nil {
		msg := "provider model handoff config swap failed; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff write bootstrap: %w; retry setup", err)
	}
	if err := b.redeployBundle(ctx, "litellm"); err != nil {
		msg := "LiteLLM restart failed during handoff; retry setup"
		b.handoffSetError(ctx, msg)
		return fmt.Errorf("handoff restart litellm: %w; retry setup", err)
	}
	// Re-read inventory and prove DB-backed ownership + name availability.
	// Any failure after the restart restores the pre-handoff config (and
	// restarts once more) so the gateway keeps serving legacy routing while
	// the operator retries; without this the empty bootstrap would go live
	// with nothing behind it.
	restoreAndFail := func(msg string, err error) error {
		b.handoffSetError(ctx, msg)
		if rerr := b.restorePreHandoffYAML(); rerr != nil {
			log.Printf("handoff restore pre-handoff config failed: %v", rerr)
		} else if rerr := b.redeployBundle(ctx, "litellm"); rerr != nil {
			log.Printf("handoff restart after restore failed: %v", rerr)
		}
		return err
	}
	native, err := b.gateway.ListModels(ctx)
	if err != nil {
		msg := "LiteLLM gateway unavailable; retry setup"
		return restoreAndFail(msg, fmt.Errorf("handoff verify inventory: %w; retry setup", err))
	}
	byID := map[string]providers.GatewayDeployment{}
	byName := map[string]bool{}
	for _, d := range native {
		byID[strings.TrimSpace(d.ModelInfo.ID)] = d
		byName[strings.TrimSpace(d.ModelName)] = true
	}
	for name, id := range wantNames {
		d, ok := byID[id]
		if !ok {
			msg := "provider model handoff verify failed for alias " + name + "; retry setup"
			return restoreAndFail(msg, fmt.Errorf("handoff missing imported model %q; retry setup", name))
		}
		if d.ModelInfo.DBModel == nil || !*d.ModelInfo.DBModel {
			msg := "provider model handoff verify failed for alias " + name + "; retry setup"
			return restoreAndFail(msg, fmt.Errorf("handoff model %q not database-backed; retry setup", name))
		}
		if !byName[name] {
			msg := "provider model handoff verify failed for alias " + name + "; retry setup"
			return restoreAndFail(msg, fmt.Errorf("handoff model name %q unavailable; retry setup", name))
		}
	}
	if err := b.handoffSetPhase(ctx, handoffPhaseCutover); err != nil {
		return err
	}
	b.handoffSetError(ctx, "")
	return nil
}

// retireProviderEnv removes OMAHAB_PROVIDER_* entries once at cutover,
// preserving every other value and restarting only when changed.
func (b *Backend) retireProviderEnv(ctx context.Context) error {
	existing, err := b.readAppEnv("litellm")
	if err != nil {
		return fmt.Errorf("read litellm appenv: %w", err)
	}
	changed := false
	next := make(map[string]string, len(existing))
	for k, v := range existing {
		if strings.HasPrefix(k, providers.ProviderEnvVarPrefix) {
			changed = true
			continue
		}
		next[k] = v
	}
	if !changed {
		return nil
	}
	if err := b.writeAppEnv("litellm", next, "litellm"); err != nil {
		return fmt.Errorf("write litellm appenv: %w", err)
	}
	if err := b.redeployBundle(ctx, "litellm"); err != nil {
		return fmt.Errorf("reload litellm after provider retirement: %w", err)
	}
	return nil
}

// --- setup-models endpoints ---

func (b *Backend) handoffComplete(ctx context.Context) bool {
	return b.handoffPhase(ctx) == handoffPhaseComplete
}

func (b *Backend) handoffErrorText(ctx context.Context) string {
	v, err := b.handoffGet(ctx, handoffErrorKey)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(v)
}

// GetModelSetup returns the safe native model inventory for onboarding.
func (b *Backend) GetModelSetup(ctx context.Context) (apitypes.ModelSetupStatus, error) {
	st := apitypes.ModelSetupStatus{
		Deployments: []apitypes.ModelSetupDeployment{},
		Aliases:     []apitypes.ModelSetupAlias{},
	}
	st.ManagementURL = b.litellmManagementURL(ctx)
	complete := b.handoffComplete(ctx)
	st.MigrationComplete = complete
	if !complete {
		if msg := b.handoffErrorText(ctx); msg != "" {
			st.MigrationError = msg
		}
	}
	if b.gateway == nil {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway not configured", ErrNotConfigured))
	}
	native, err := b.gateway.ListModels(ctx)
	if err != nil {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway unavailable: %v", apitypes.ErrServiceUnavailable, err))
	}
	for _, d := range native {
		prov, mode, ok := isSelectableDeployment(d)
		if !ok {
			continue
		}
		modelStr, _ := d.LitellmParams["model"].(string)
		st.Deployments = append(st.Deployments, apitypes.ModelSetupDeployment{
			ID:       strings.TrimSpace(d.ModelInfo.ID),
			Name:     strings.TrimSpace(d.ModelName),
			Model:    strings.TrimSpace(modelStr),
			Provider: prov,
			Mode:     mode,
		})
	}
	byNameProviders := map[string][]string{}
	byNameSeen := map[string]map[string]bool{}
	for _, d := range native {
		name := strings.TrimSpace(d.ModelName)
		if name == "" {
			continue
		}
		prov, ok := resolveProviderIdentity(d)
		if !ok {
			prov = "unknown"
		}
		if byNameSeen[name] == nil {
			byNameSeen[name] = map[string]bool{}
		}
		if !byNameSeen[name][prov] {
			byNameSeen[name][prov] = true
			byNameProviders[name] = append(byNameProviders[name], prov)
		}
	}
	for _, name := range modelSetupAliases {
		provs := byNameProviders[name]
		if provs == nil {
			provs = []string{}
		}
		st.Aliases = append(st.Aliases, apitypes.ModelSetupAlias{
			Name:       name,
			Configured: len(byNameProviders[name]) > 0,
			Providers:  provs,
		})
	}
	return st, nil
}

// SeedModelAliases seeds missing chat-role aliases from one native deployment.
func (b *Backend) SeedModelAliases(ctx context.Context, req apitypes.SeedModelAliasesRequest) (apitypes.ModelSetupStatus, error) {
	seedMu.Lock()
	defer seedMu.Unlock()
	modelID := strings.TrimSpace(req.ModelID)
	if modelID == "" {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: model_id is required", apitypes.ErrValidation))
	}
	if !b.handoffComplete(ctx) {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: migration incomplete; retry setup", apitypes.ErrConflict))
	}
	if b.gateway == nil {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway unavailable", apitypes.ErrServiceUnavailable))
	}
	src, err := b.gateway.GetModel(ctx, modelID)
	if err != nil {
		if errors.Is(err, providers.ErrNotFound) || strings.Contains(strings.ToLower(err.Error()), "not found") {
			return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: model %q not found", apitypes.ErrNotFound, modelID))
		}
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway unavailable: %v", apitypes.ErrServiceUnavailable, err))
	}
	if _, _, ok := isSelectableDeployment(src); !ok {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: model %q is not a selectable chat deployment", apitypes.ErrValidation, modelID))
	}
	native, err := b.gateway.ListModels(ctx)
	if err != nil {
		return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway unavailable: %v", apitypes.ErrServiceUnavailable, err))
	}
	presentNames := map[string]bool{}
	byID := map[string]providers.GatewayDeployment{}
	for _, d := range native {
		presentNames[strings.TrimSpace(d.ModelName)] = true
		byID[strings.TrimSpace(d.ModelInfo.ID)] = d
	}
	var missing []string
	for _, role := range seedRoles {
		if !presentNames[role] {
			missing = append(missing, role)
		}
	}
	if len(missing) == 0 {
		return b.GetModelSetup(ctx)
	}
	needsCredential := !isOAuthSource(src)
	credName := ""
	if needsCredential {
		credName = seedCredentialName(modelID)
		gwCreds, err := b.gateway.ListGatewayCredentials(ctx)
		if err != nil {
			return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway unavailable: %v", apitypes.ErrServiceUnavailable, err))
		}
		found := false
		for _, gc := range gwCreds {
			if strings.TrimSpace(gc.CredentialName) != credName {
				continue
			}
			found = true
			if strings.TrimSpace(gc.CredentialInfo["omahab_seed_source_id"]) != modelID {
				return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: credential %q already exists for a different source model; delete it in LiteLLM or re-seed from the original source", apitypes.ErrConflict, credName))
			}
			break
		}
		if !found {
			in := providers.GatewayCredentialInput{
				CredentialName: credName,
				CredentialInfo: map[string]string{"omahab_seed_source_id": modelID},
				ModelID:        modelID,
			}
			if err := b.gateway.CreateGatewayCredential(ctx, in); err != nil {
				return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("seed credential %q: %w", credName, err))
			}
		}
	}
	srcParams := src.LitellmParams
	if srcParams == nil {
		srcParams = map[string]any{}
	}
	for _, role := range missing {
		// Skip any name that appeared since the pre-creation inventory read.
		fresh, err := b.gateway.ListModels(ctx)
		if err != nil {
			return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: gateway unavailable: %v", apitypes.ErrServiceUnavailable, err))
		}
		freshNames := map[string]bool{}
		freshIDs := map[string]providers.GatewayDeployment{}
		for _, d := range fresh {
			freshNames[strings.TrimSpace(d.ModelName)] = true
			freshIDs[strings.TrimSpace(d.ModelInfo.ID)] = d
		}
		if freshNames[role] {
			continue
		}
		roleID := seedRoleID(role)
		if d, ok := freshIDs[roleID]; ok && strings.TrimSpace(d.ModelName) != role {
			return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: model id %q already in use", apitypes.ErrConflict, roleID))
		}
		if _, ok := freshIDs[roleID]; ok {
			continue // deterministic object already present
		}
		params := map[string]any{}
		if m, ok := srcParams["model"].(string); ok && strings.TrimSpace(m) != "" {
			params["model"] = strings.TrimSpace(m)
		} else {
			return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("%w: source model %q has no model", apitypes.ErrValidation, modelID))
		}
		for _, k := range []string{"custom_llm_provider", "use_xai_oauth", "use_chat_completions_api", "api_base", "api_version", "region_name"} {
			if v, ok := srcParams[k]; ok {
				params[k] = v
			}
		}
		if needsCredential {
			params["litellm_credential_name"] = credName
		}
		dbTrue := true
		dep := providers.GatewayDeployment{
			ModelName:     role,
			LitellmParams: params,
			ModelInfo: providers.GatewayModelInfo{
				ID:              roleID,
				DBModel:         &dbTrue,
				Mode:            deploymentMode(src),
				LitellmProvider: strings.TrimSpace(src.ModelInfo.LitellmProvider),
			},
		}
		// Preserve explicit provider prefix signal when info provider empty.
		if strings.TrimSpace(dep.ModelInfo.LitellmProvider) == "" {
			if prov, ok := resolveProviderIdentity(src); ok {
				if i := strings.Index(prov, "@"); i >= 0 {
					prov = prov[:i]
				}
				dep.ModelInfo.LitellmProvider = prov
			}
		}
		if err := b.gateway.CreateModel(ctx, dep); err != nil {
			return apitypes.ModelSetupStatus{}, translateError(fmt.Errorf("seed alias %q: %w", role, err))
		}
	}
	return b.GetModelSetup(ctx)
}

func isOAuthSource(d providers.GatewayDeployment) bool {
	if d.LitellmParams != nil {
		if v, ok := d.LitellmParams["use_xai_oauth"].(bool); ok && v {
			return true
		}
	}
	modelStr := ""
	if d.LitellmParams != nil {
		modelStr, _ = d.LitellmParams["model"].(string)
	}
	lower := strings.ToLower(strings.TrimSpace(modelStr))
	prov := strings.ToLower(strings.TrimSpace(d.ModelInfo.LitellmProvider))
	if cp, ok := d.LitellmParams["custom_llm_provider"].(string); ok && strings.TrimSpace(cp) != "" {
		prov = strings.ToLower(strings.TrimSpace(cp))
	}
	if strings.HasPrefix(lower, "chatgpt/") || prov == providers.ProviderChatGPT {
		// ChatGPT subscription uses token files, no API key.
		if _, hasKey := d.LitellmParams["api_key"]; !hasKey {
			if _, hasCred := d.LitellmParams["litellm_credential_name"]; !hasCred {
				return true
			}
		}
	}
	if strings.HasPrefix(lower, "xai/") || prov == providers.ProviderXAI {
		if _, hasKey := d.LitellmParams["api_key"]; !hasKey {
			if _, hasCred := d.LitellmParams["litellm_credential_name"]; !hasCred {
				return true
			}
		}
	}
	return false
}

// nativeAliasAvailable reports whether a native omahab/* model_name deployment
// exists. It backs Karakeep gating after the handoff (no SQLite fallback).
func (b *Backend) nativeAliasAvailable(ctx context.Context, alias string) bool {
	if b.gateway == nil {
		return false
	}
	models, err := b.gateway.ListModels(ctx)
	if err != nil {
		return false
	}
	for _, d := range models {
		if strings.TrimSpace(d.ModelName) == strings.TrimSpace(alias) {
			return true
		}
	}
	return false
}

// nativeProbeModel chooses a live native deployment for OAuth probing,
// preferring omahab/fast. Empty means no native model is configured.
func (b *Backend) nativeProbeModel(ctx context.Context, provider string) string {
	if b.gateway == nil {
		return ""
	}
	models, err := b.gateway.ListModels(ctx)
	if err != nil || len(models) == 0 {
		return ""
	}
	provider = strings.ToLower(strings.TrimSpace(provider))
	fallback := ""
	for _, d := range models {
		ident, ok := resolveProviderIdentity(d)
		if !ok {
			continue
		}
		base := ident
		if i := strings.Index(base, "@"); i >= 0 {
			base = base[:i]
		}
		if !strings.EqualFold(base, provider) {
			continue
		}
		name := strings.TrimSpace(d.ModelName)
		if name == "" {
			continue
		}
		if name == providers.AliasFast {
			return name
		}
		if fallback == "" {
			fallback = name
		}
	}
	return fallback
}
