version: "2"

formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

linters:
  enable:
    - modernize
  disable:
    - errcheck
