// Code generated by sqlc. DO NOT EDIT.
// Regenerate with: sqlc generate
// versions:
//   sqlc v2.16.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

// DBTX is the database interface expected by the sqlc-generated Queries.
// It is satisfied by *sql.DB and *sql.Tx when using database/sql with
// modernc.org/sqlite, which the store package uses so no C toolchain is
// required. sqlc generate regenerates this file; do not edit by hand.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// Queries holds the DB handle for generated methods. Create one with New.
// Generated queries are named after the `-- name:` annotations in query.sql.
type Queries struct {
	db DBTX
}

// New returns a Queries backed by db. The DB may be a *sql.DB for
// non-transactional work or a *sql.Tx for transactional sequences; use
// WithTx to bind a Queries to an active transaction.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a copy of Queries whose underlying DBTX is tx. It is the
// sqlc idiom for running generated queries inside an explicit transaction:
//   tx, _ := s.db.BeginTx(ctx, nil)
//   q := New(s.db).WithTx(tx)
//   defer tx.Rollback()
//   // ... q.* calls ...
//   tx.Commit()
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
