// Code generated by sqlc. DO NOT EDIT.
// Regenerate with: sqlc generate
// versions:
//   sqlc v2.16.0
// source: schema.sql

package store

// Instance corresponds to the `instance` table created by core-001-instance.
// It is the sqlc row type derived from the schema; callers that need
// domain validation should convert to/from domain.Instance via the helpers
// in instances.go (FormatTime/ParseTime). sqlc generate regenerates this.
type Instance struct {
	Singleton     int64  `db:"singleton" json:"singleton"`
	ID            string `db:"id" json:"id"`
	Domain        string `db:"domain" json:"domain"`
	Tailnet       string `db:"tailnet" json:"tailnet"`
	TailscaleIP   string `db:"tailscale_ip" json:"tailscale_ip"`
	AssistantName string `db:"assistant_name" json:"assistant_name"`
	AssistantSlug string `db:"assistant_slug" json:"assistant_slug"`
	CreatedAt     string `db:"created_at" json:"created_at"`
}

// SchemaMigration corresponds to the `schema_migrations` table that tracks
// which named migrations have been applied. It mirrors the table created by
// CreateSchemaMigrations / migrate.go's ad-hoc creation.
type SchemaMigration struct {
	Name      string `db:"name" json:"name"`
	AppliedAt string `db:"applied_at" json:"applied_at"`
}
