// Code generated by sqlc. DO NOT EDIT.
// Regenerate with: sqlc generate
// versions:
//   sqlc v2.16.0
// source: query.sql

package store

import (
	"context"
)

// Querier is the interface exposed by the sqlc-generated Queries. It lists
// every method generated from query.sql. Controllers that wish to mock the
// store may depend on this interface instead of *Queries. Emit via
// emit_interface: true in sqlc.yaml.
type Querier interface {
	CheckSchemaMigration(ctx context.Context, name string) (bool, error)
	CreateInstance(ctx context.Context, arg CreateInstanceParams) error
	CreateSchemaMigrations(ctx context.Context) error
	GetInstance(ctx context.Context) (GetInstanceRow, error)
	GetInstanceIdentity(ctx context.Context) (GetInstanceIdentityRow, error)
	InsertSchemaMigration(ctx context.Context, arg InsertSchemaMigrationParams) error
	ListSchemaMigrations(ctx context.Context) ([]SchemaMigration, error)
	UpdateInstance(ctx context.Context, arg UpdateInstanceParams) error
}

var _ Querier = (*Queries)(nil)
