// Code generated by sqlc. DO NOT EDIT.
// Regenerate with: sqlc generate
// versions:
//   sqlc v2.16.0
// source: query.sql

package store

import (
	"context"
)

// --- Params and row types ---

// GetInstanceRow is the row returned by GetInstance.
type GetInstanceRow struct {
	ID            string `db:"id" json:"id"`
	Domain        string `db:"domain" json:"domain"`
	Tailnet       string `db:"tailnet" json:"tailnet"`
	TailscaleIP   string `db:"tailscale_ip" json:"tailscale_ip"`
	AssistantName string `db:"assistant_name" json:"assistant_name"`
	AssistantSlug string `db:"assistant_slug" json:"assistant_slug"`
	CreatedAt     string `db:"created_at" json:"created_at"`
}

// GetInstanceIdentityRow is the row returned by GetInstanceIdentity.
type GetInstanceIdentityRow struct {
	ID        string `db:"id" json:"id"`
	CreatedAt string `db:"created_at" json:"created_at"`
}

// CreateInstanceParams bundles the columns for CreateInstance.
type CreateInstanceParams struct {
	ID            string `db:"id" json:"id"`
	Domain        string `db:"domain" json:"domain"`
	Tailnet       string `db:"tailnet" json:"tailnet"`
	TailscaleIP   string `db:"tailscale_ip" json:"tailscale_ip"`
	AssistantName string `db:"assistant_name" json:"assistant_name"`
	AssistantSlug string `db:"assistant_slug" json:"assistant_slug"`
	CreatedAt     string `db:"created_at" json:"created_at"`
}

// UpdateInstanceParams bundles the columns for UpdateInstance.
type UpdateInstanceParams struct {
	Domain        string `db:"domain" json:"domain"`
	Tailnet       string `db:"tailnet" json:"tailnet"`
	TailscaleIP   string `db:"tailscale_ip" json:"tailscale_ip"`
	AssistantName string `db:"assistant_name" json:"assistant_name"`
	AssistantSlug string `db:"assistant_slug" json:"assistant_slug"`
}

// InsertSchemaMigrationParams bundles the columns for InsertSchemaMigration.
type InsertSchemaMigrationParams struct {
	Name      string `db:"name" json:"name"`
	AppliedAt string `db:"applied_at" json:"applied_at"`
}

// --- Query constants ---

const getInstance = `-- name: GetInstance :one
SELECT id, domain, tailnet, tailscale_ip, assistant_name, assistant_slug, created_at
FROM instance
WHERE singleton = 1`

const getInstanceIdentity = `-- name: GetInstanceIdentity :one
SELECT id, created_at
FROM instance
WHERE singleton = 1`

const createInstance = `-- name: CreateInstance :exec
INSERT INTO instance (singleton, id, domain, tailnet, tailscale_ip, assistant_name, assistant_slug, created_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?)`

const updateInstance = `-- name: UpdateInstance :exec
UPDATE instance
SET domain = ?, tailnet = ?, tailscale_ip = ?, assistant_name = ?, assistant_slug = ?
WHERE singleton = 1`

const createSchemaMigrations = `-- name: CreateSchemaMigrations :exec
CREATE TABLE IF NOT EXISTS schema_migrations (
    name TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
)`

const checkSchemaMigration = `-- name: CheckSchemaMigration :one
SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE name = ?)`

const insertSchemaMigration = `-- name: InsertSchemaMigration :exec
INSERT INTO schema_migrations (name, applied_at) VALUES (?, ?)`

const listSchemaMigrations = `-- name: ListSchemaMigrations :many
SELECT name, applied_at FROM schema_migrations ORDER BY name`

// --- Generated query methods ---

// GetInstance returns the singleton instance row. It fails with sql.ErrNoRows
// when no instance has been saved yet; callers map that to ErrNotFound.
func (q *Queries) GetInstance(ctx context.Context) (GetInstanceRow, error) {
	row := q.db.QueryRowContext(ctx, getInstance)
	var i GetInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Tailnet,
		&i.TailscaleIP,
		&i.AssistantName,
		&i.AssistantSlug,
		&i.CreatedAt,
	)
	return i, err
}

// GetInstanceIdentity returns only the stable identity fields used by
// SaveInstance to detect conflicts without re-validating the full row.
func (q *Queries) GetInstanceIdentity(ctx context.Context) (GetInstanceIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceIdentity)
	var i GetInstanceIdentityRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

// CreateInstance inserts the singleton instance row. The singleton column is
// fixed to 1 in the SQL so callers do not provide it.
func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, createInstance,
		arg.ID,
		arg.Domain,
		arg.Tailnet,
		arg.TailscaleIP,
		arg.AssistantName,
		arg.AssistantSlug,
		arg.CreatedAt,
	)
	return err
}

// UpdateInstance updates the mutable columns of the singleton instance row.
func (q *Queries) UpdateInstance(ctx context.Context, arg UpdateInstanceParams) error {
	_, err := q.db.ExecContext(ctx, updateInstance,
		arg.Domain,
		arg.Tailnet,
		arg.TailscaleIP,
		arg.AssistantName,
		arg.AssistantSlug,
	)
	return err
}

// CreateSchemaMigrations ensures the schema_migrations table exists.
// It is idempotent and safe to call on every Migrate.
func (q *Queries) CreateSchemaMigrations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSchemaMigrations)
	return err
}

// CheckSchemaMigration reports whether a migration name is already recorded.
// The underlying SQL uses SELECT EXISTS, which always returns a single 0/1 row.
func (q *Queries) CheckSchemaMigration(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSchemaMigration, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

// InsertSchemaMigration records a newly applied migration.
func (q *Queries) InsertSchemaMigration(ctx context.Context, arg InsertSchemaMigrationParams) error {
	_, err := q.db.ExecContext(ctx, insertSchemaMigration, arg.Name, arg.AppliedAt)
	return err
}

// ListSchemaMigrations returns all recorded migrations ordered by name.
func (q *Queries) ListSchemaMigrations(ctx context.Context) ([]SchemaMigration, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchemaMigration
	for rows.Next() {
		var i SchemaMigration
		if err := rows.Scan(&i.Name, &i.AppliedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
