d /etc/omahab 0755 root root - -
d /var/lib/omahab 0700 root root - -
d /var/lib/omahab/secrets 0700 root root - -
d /srv/omahab 0755 root root - -
d /srv/omahab/apps 0755 root root - -
d /srv/omahab/projects 0755 root root - -
d /srv/omahab/sync 0755 root root - -
d /srv/omahab/workspaces 0755 root root - -
d /srv/omahab/backups 0755 root root - -
d /srv/omahab/derived-indexes 0755 root root - -
d /var/log/omahab 0750 root root - -
d /var/cache/omahab 0755 root root - -
